[package]
name = "url-prefix"
version = "1.3.1"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/url-prefix"
homepage = "https://magiclen.org/url-prefix"
keywords = ["url", "prefix", "http", "https", "ftp"]
categories = ["value-formatting"]
description= "A library for creating URL prefix strings."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/url-prefix", branch = "master" }
appveyor = { repository = "magiclen/url-prefix", branch = "master", service = "github" }

[dependencies]
validators = { version = ">=0.18,<0.20", optional = true }

[features]
validator = ["validators"]

[package.metadata.docs.rs]
all-features = true